import { readFile, readdir } from "node:fs/promises";
import { basename, dirname, join, relative, resolve } from "node:path";

const noticeName = /^(?:licen[cs]es?|copying|notices?|copyright)(?:[._-].*)?$/i;
const licenseName = /^(?:licen[cs]es?|copying)(?:[._-].*)?$/i;

async function findPackage(input, root) {
  let directory = dirname(resolve(root, input));
  while (basename(directory) !== "node_modules") {
    try {
      const manifest = JSON.parse(
        await readFile(join(directory, "package.json"), "utf8"),
      );
      // Published subdirectories sometimes contain only a module-type manifest.
      if (manifest.name) return { directory, manifest };
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    const parent = dirname(directory);
    if (parent === directory) break;
    directory = parent;
  }
  throw new Error(`Cannot find package.json for bundled dependency: ${input}`);
}

async function packageNotices({ directory, manifest }) {
  const { name, version, license } = manifest;
  if (!version || typeof license !== "string" || !license.trim())
    throw new Error(`Missing version or license metadata for ${name}`);

  const notices = [];
  let hasLicense = false;
  async function collect(
    folder,
    noticeDirectory = false,
    licenseDirectory = false,
  ) {
    for (const entry of await readdir(folder, { withFileTypes: true })) {
      if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
      const path = join(folder, entry.name);
      if (entry.isDirectory()) {
        await collect(
          path,
          noticeDirectory || noticeName.test(entry.name),
          licenseDirectory || licenseName.test(entry.name),
        );
      } else if (
        entry.isFile() &&
        (noticeDirectory || noticeName.test(entry.name))
      ) {
        const text = (await readFile(path, "utf8")).replace(/\r\n?/g, "\n");
        if (!text.trim())
          throw new Error(`Empty notice file for ${name}: ${path}`);
        hasLicense ||= licenseDirectory || licenseName.test(entry.name);
        notices.push({
          path: relative(directory, path).replaceAll("\\", "/"),
          text,
        });
      }
    }
  }
  await collect(directory);
  if (!hasLicense)
    throw new Error(
      `Missing license file for bundled dependency ${name}@${version}`,
    );

  notices.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return [
    `${name}@${version}`,
    `License: ${license}`,
    "",
    ...notices.map(
      ({ path, text }) =>
        `--- ${path} ---\n${text}${text.endsWith("\n") ? "" : "\n"}`,
    ),
  ].join("\n");
}

// Only output contributors count: esbuild's top-level inputs also include
// modules that were entirely tree-shaken out of the shipped bundles.
export async function generateThirdPartyNotices(
  metafiles,
  root = process.cwd(),
) {
  const packages = new Map();
  const inputs = new Set();
  for (const metafile of metafiles) {
    for (const output of Object.values(metafile.outputs)) {
      for (const [input, details] of Object.entries(output.inputs)) {
        if (
          details.bytesInOutput > 0 &&
          input.replaceAll("\\", "/").split("/").includes("node_modules")
        )
          inputs.add(input);
      }
    }
  }
  for (const input of [...inputs].sort()) {
    const dependency = await findPackage(input, root);
    packages.set(dependency.directory, dependency);
  }
  const sections = [
    ...new Set(await Promise.all([...packages.values()].map(packageNotices))),
  ].sort();
  return (
    [
      "THIRD-PARTY NOTICES FOR dolu_fivem_mcp",
      "",
      "Generated by scripts/notices.mjs during npm run build. Do not edit.",
      "Only dependencies contributing bytes to the runtime bundles are included.",
      "",
      ...sections.map((section) => `${"=".repeat(80)}\n${section}`),
    ]
      .join("\n")
      .trimEnd() + "\n"
  );
}
